"""
Builds src/lib/data/airports.js from the OpenFlights airport database.

Download https://raw.githubusercontent.com/jpatokal/openflights/master/data/airports.dat
and run:

    python scripts/generate-airports.py path/to/airports.dat

Only airports with a valid IATA code are kept. Each row becomes
[code, city, airport, country], which the flight search renders as
"City - Airport - CODE" (e.g. "London - Heathrow - LHR").
"""

import csv
import json
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "lib" / "data" / "airports.js"

# OpenFlights files some airports under a nearby town; travellers search by the
# city they are flying to.
CITY_OVERRIDES = {
    "DSS": "Dakar",
}

# Corrections to OpenFlights airport names.
NAME_OVERRIDES = {
    "LHE": "Allama Iqbal International",
    "ISB": "Islamabad International",
    "LBA": "Leeds Bradford",
}

# Metropolitan codes that search every airport in a city.
METRO_CODES = [
    ("LON", "London", "United Kingdom"),
    ("NYC", "New York", "United States"),
    ("PAR", "Paris", "France"),
    ("MIL", "Milan", "Italy"),
    ("ROM", "Rome", "Italy"),
    ("CHI", "Chicago", "United States"),
    ("WAS", "Washington", "United States"),
    ("YTO", "Toronto", "Canada"),
    ("TYO", "Tokyo", "Japan"),
    ("SEL", "Seoul", "South Korea"),
    ("BJS", "Beijing", "China"),
    ("MOW", "Moscow", "Russia"),
    ("STO", "Stockholm", "Sweden"),
    ("SAO", "Sao Paulo", "Brazil"),
]

# Words that are not enough to identify an airport once the city is removed,
# e.g. "Banjul International Airport" must stay "Banjul International".
GENERIC_REMAINDERS = {
    "international",
    "intl",
    "regional",
    "municipal",
    "airport",
    "airfield",
    "air base",
    "airbase",
}


def airport_name(name, city):
    full = name.strip()
    name = re.sub(r"\s+Airport$", "", full)
    if name.lower() == city.lower():
        # "Manchester Airport" reads better than "Manchester - Manchester".
        return full
    if city and name.lower().startswith(city.lower() + " "):
        remainder = name[len(city) + 1 :].strip()
        if remainder.lower() not in GENERIC_REMAINDERS:
            return remainder
    return name


def main(src):
    rows = {}
    with open(src, encoding="utf-8") as fh:
        for rec in csv.reader(fh):
            _, name, city, country, iata = rec[:5]
            kind = rec[12] if len(rec) > 12 else "airport"
            if kind != "airport" or not re.fullmatch(r"[A-Z]{3}", iata or ""):
                continue
            city = CITY_OVERRIDES.get(iata, city.strip() or name.strip())
            name = NAME_OVERRIDES.get(iata) or airport_name(name, city)
            rows.setdefault(iata, [iata, city, name, country.strip()])

    for code, city, country in METRO_CODES:
        rows.setdefault(code, [code, city, "All airports", country])

    data = sorted(rows.values(), key=lambda r: (r[1].lower(), r[0]))
    body = ",\n".join("  " + json.dumps(r, ensure_ascii=False) for r in data)
    OUT.write_text(
        "// GENERATED by scripts/generate-airports.py from the OpenFlights airport\n"
        "// database (https://openflights.org/data). Re-generate rather than editing.\n"
        "// Rows are [code, city, airport, country].\n"
        f"const ROWS = [\n{body},\n];\n\n"
        "export const AIRPORTS = ROWS.map(([code, city, airport, country]) => ({\n"
        "  code,\n"
        "  city,\n"
        "  airport,\n"
        "  country,\n"
        "}));\n\n"
        "export const airportLabel = (item) =>\n"
        "  `${item.city} - ${item.airport} - ${item.code}`;\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {len(data)} airports to {OUT}")


if __name__ == "__main__":
    main(sys.argv[1])
