export const CITY_LIST = [
  { city: "Abu Dhabi", code: "AUH" },
  { city: "Accra", code: "ACC" },
  { city: "Addis Ababa", code: "ADD" },
  { city: "Adelaide", code: "ADL" },
  { city: "Amsterdam", code: "AMS" },
  { city: "Bangkok", code: "BKK" },
  { city: "Barcelona", code: "BCN" },
  { city: "Beijing", code: "PEK" },
  { city: "Berlin", code: "BER" },
  { city: "Boston", code: "BOS" },
  { city: "Cape Town", code: "CPT" },
  { city: "Chicago", code: "ORD" },
  { city: "Delhi", code: "DEL" },
  { city: "Dubai", code: "DXB" },
  { city: "Geneva", code: "GVA" },
  { city: "Hong Kong", code: "HKG" },
  { city: "Istanbul", code: "IST" },
  { city: "Jakarta", code: "CGK" },
  { city: "Johannesburg", code: "JNB" },
  { city: "London", code: "LHR" },
  { city: "Los Angeles", code: "LAX" },
  { city: "Madrid", code: "MAD" },
  { city: "Manila", code: "MNL" },
  { city: "Miami", code: "MIA" },
  { city: "Moscow", code: "SVO" },
  { city: "Mumbai", code: "BOM" },
  { city: "New York", code: "JFK" },
  { city: "Paris", code: "CDG" },
  { city: "Rome", code: "FCO" },
  { city: "San Francisco", code: "SFO" },
  { city: "Singapore", code: "SIN" },
  { city: "Sydney", code: "SYD" },
  { city: "Tokyo", code: "HND" },
  { city: "Toronto", code: "YYZ" },
  { city: "Vancouver", code: "YVR" },
  { city: "Warsaw", code: "WAW" },
  { city: "Zurich", code: "ZRH" },
];
