name: Mirror Org Repo to Personal Repo

on:
  push:
    branches:
      - main
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Org Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false   # 🔥 IMPORTANT

      - name: Push to Personal Repository
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote add personal https://x-access-token:${PERSONAL_ACCESS_TOKEN}@github.com/Travellia/Travellia-rewrite.git
          git push personal ${{ github.ref_name }} --force